== makebwpdf

Convert a series of image files to a multi-page bilevel (i.e. black and
white) PDF.

Requires: econvert (from https://exactcode.com/opensource/exactimage/ ),
tiffcp, tiff2pdf, ImageMagick convert, and pdfsandwich.

By Pontus Lurcock, 2017-2020 (pont -at- talvi.net).
Released under the MIT license (see accompanying file LICENSE for details).

....
usage: makebwpdf.py [-h] [--brightness BRIGHTNESS] --output OUTPUT [--append]
                    [--papersize PAPERSIZE] [--tempdir TEMPDIR]
                    [--rotate ROTATE] [--languages LANGUAGES] [--scan]
                    [--correct-position]
                    [input_files [input_files ...]]

positional arguments:
  input_files           input filename

optional arguments:
  -h, --help            show this help message and exit
  --brightness BRIGHTNESS, -b BRIGHTNESS
                        Brightness adjustment (default: 0)
  --output OUTPUT, -o OUTPUT
                        Output filename (required)
  --append, -a          Append page(s) to existing PDF output file
  --papersize PAPERSIZE, -p PAPERSIZE
                        Paper size (passed to tiff2pdf)
  --tempdir TEMPDIR, -t TEMPDIR
                        Use TEMPDIR as temporary directory
  --rotate ROTATE, -r ROTATE
                        Rotate pages by the given number of degrees
  --languages LANGUAGES, -l LANGUAGES
                        OCR the PDF in these languages (e.g. 'eng+deu')
  --scan, -s            Acquire image from scanner (ignores input files)
  --correct-position, -c
                        Correct positioning for scans from Brother MFC-L2710DW
....
