== makebwpdf

Convert a series of image files, or data from a scanner, to a multi-page
bilevel (i.e. black and white) PDF with optional OCR. makebwpdf can also
fix the incorrect page positioning for A4 and A5 scans produced by the
Brother MFC-L2710DW multifunction device.

Requires: https://exactcode.com/opensource/exactimage/[econvert],
tiffcp, tiff2pdf, ocrmypdf, pdftk, and PIL.

By Pontus Lurcock, 2017-2020 (pont -at- talvi.net).
Released under the MIT license (see accompanying file LICENSE for details).

=== Installation

On Ubuntu 20.04, the requirements can be installed with
....
sudo apt install python3-pip python3-pil exactimage libtiff-tools ocrmypdf pdftk
....

The file `makebwpdf.py` can be run directly. It can also be installed by
running `python3 -m pip install makebwpdf/` from the _parent_ directory of
the repository, which will make the command `makebwpdf` available on the
execution path. `python3 -m pip install --user makebwpdf/` will install it
for the current user only.

To uninstall, use `python3 -m pip uninstall makebwpdf`.

=== Usage
....
usage: makebwpdf [-h] [--brightness BRIGHTNESS] --output OUTPUT [--append]
                 [--papersize PAPERSIZE] [--tempdir TEMPDIR] [--rotate ROTATE]
                 [--languages LANGUAGES] [--scan] [--device DEVICE]
                 [--correct-position] [--invert]
                 [input_files [input_files ...]]

positional arguments:
  input_files           input filename

optional arguments:
  -h, --help            show this help message and exit
  --brightness BRIGHTNESS, -b BRIGHTNESS
                        Brightness adjustment (default: 0)
  --output OUTPUT, -o OUTPUT
                        Output filename (required)
  --append, -a          Append page(s) to existing PDF output file
  --papersize PAPERSIZE, -p PAPERSIZE
                        Paper size
  --tempdir TEMPDIR, -t TEMPDIR
                        Use TEMPDIR as temporary directory
  --rotate ROTATE, -r ROTATE
                        Rotate pages by the given number of degrees
  --languages LANGUAGES, -l LANGUAGES
                        OCR the PDF in these languages (e.g. 'eng+deu')
  --scan, -s            Acquire image from scanner (ignores input files)
  --device DEVICE, -d DEVICE
                        Scanner device (implies --scan)
  --correct-position, -c
                        Correct positioning for scans from Brother MFC-L2710DW
  --invert, -i          Invert colours
....
