== makebwpdf

Convert a series of image files to a multi-page bilevel (i.e. black and
white) PDF.

Requires: https://exactcode.com/opensource/exactimage/[econvert],
tiffcp, tiff2pdf, pdfsandwich, pdftk, and PIL.

By Pontus Lurcock, 2017-2020 (pont -at- talvi.net).
Released under the MIT license (see accompanying file LICENSE for details).

=== Installation

The file `makebwpdf.py` can be run directly. It can also be installed by
running `pip3 install makebwpdf/` from the parent directory of the repository,
which will make the command `makebwpdf` available on the execution path.
`pip3 install --user makebwpdf` will install it for the current user only.
To uninstall, use `pip3 uninstall makebwpdf`.

=== Usage
....
usage: makebwpdf [-h] [--brightness BRIGHTNESS] --output OUTPUT [--append]
                 [--papersize PAPERSIZE] [--tempdir TEMPDIR] [--rotate ROTATE]
                 [--languages LANGUAGES] [--scan] [--correct-position]
                 [input_files [input_files ...]]

positional arguments:
  input_files           input filename

optional arguments:
  -h, --help            show this help message and exit
  --brightness BRIGHTNESS, -b BRIGHTNESS
                        Brightness adjustment (default: 0)
  --output OUTPUT, -o OUTPUT
                        Output filename (required)
  --append, -a          Append page(s) to existing PDF output file
  --papersize PAPERSIZE, -p PAPERSIZE
                        Paper size (passed to tiff2pdf)
  --tempdir TEMPDIR, -t TEMPDIR
                        Use TEMPDIR as temporary directory
  --rotate ROTATE, -r ROTATE
                        Rotate pages by the given number of degrees
  --languages LANGUAGES, -l LANGUAGES
                        OCR the PDF in these languages (e.g. 'eng+deu')
  --scan, -s            Acquire image from scanner (ignores input files)
  --correct-position, -c
                        Correct positioning for scans from Brother MFC-L2710DW
....
